### ISSUE TITLE
z_min and z_max in outputs do not match set values

### ISSUE THREAD

**Issue by bryantbenson** [tdk111/3dfast#1]
In the smk_transform_data_v1.c file, redshift values (zmin, zmax, npz, zpzdz) for the catalog are manually input in lines 174-178.  However, the zmin and zmax values are reset to 99999 and -99999 respectively in lines 525 and 526.  They are then recalculated from the redshift array, which holds the original bin value with the highest redshift probability for each galaxy.  These new zmin and zmax values are then used to make the fine r-grid and calculate n(z) binned in redshifts (lines 545-615).

For the catalog that I am working with, we have 500 redshift bins equally spaced between 0.01 and 5.0, but we are only including galaxies with a maximum probability redshift > 0.3.  When I run this catalog through the 3dfast code, the output tells me that there are 500 bins equally spaced between 0.3 and 4.9.  If these are indeed the bins being used in calculations, then probability information from the catalog is being assigned to the wrong redshifts.

**Comment by tdk111** [comment]
Thanks Bryant, 

This is mainly lines 523-534 in the smk_transform_data_v1.c file where zmin and zmax are re-calculated from the maximum redshift probability bin (below). This was used to ensure the redshift range was sufficient for the calculation, but in your specific case it is restricting the range. I think this is either appropriate or not depending on the definitions and nature of the p(z). The important thing is that zmax and zmin span the range of value required. 

So I would simply comment out the the last two lines below, that I believe should solve the problem.

> rmax=-99999.;
> rmin= 99999.;
> zmax=-99999.;
> zmin= 99999.;
> numrvalues=(double *_)calloc(3,sizeof(double_));
> for (i=0;i<3;i++) numrvalues[i]=(double *)calloc(nobj,sizeof(double)); //for fits write
> for (i=0;i<nobj;i++) { 
>    rg[i]=dist(cosmof,redshift[i]);
>    if (rg[i]>rmax) rmax=rg[i];
>    if (rg[i]<rmin) rmin=rg[i];
>    if (redshift[i] > zmax) zmax=redshift[i];
>    if (redshift[i] < zmin) zmin=redshift[i];
